name: OSV-Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "13 6 * * 3"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: osv-scanner-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    name: Scan dependencies via OSV
    if: github.event.repository.private == false
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1 # v2.5.0
    with:
      scan-args: |-
        --recursive
        --skip-git
        ./
      results-file-name: osv-results.sarif
    permissions:
      contents: read
      security-events: write
      actions: read
